### ISSUE TITLE
DataConfig and EpisodeConfig constructors should directly accept arguments as opposed to encapsulated in an argparse.Namespace

### ISSUE THREAD

**Issue by jfb54** [mboudiaf/pytorch-meta-dataset#1]
First of all, thanks for writing this library. I have been using the official MetaDataset TensorFlow reader in conjunction with PyTorch (which works, but is very resource hungry), so I thought I would try out your library. It now works, but I needed to work around several issues. I'll file a series of issues for these.

The first issue I hit was the fact that the DataConfig and EpisodeConfig constructors took their arguments via an argparse.Namespace. This won't work for a real meta-dataset application as you typically need to set up several DataLoaders (say for train, validate and test) and you usually need to specify different parameters for each (e.g. max_support_set_size). My workaround was to modify your code and make constructors with a conventional set of arguments. Would be great if you could make the change!

**Comment by mboudiaf** [comment]
Hi @jfb54,

Thanks a lot for raising those issues, which I'm sure will improve this repo. I will try to address / make the necessary changes gradually over the coming days. 

Starting with the first issue. I agree making the arguments explicit is a better idea. I will modify to make the necessary changes over the coming days. Thanks again.

**Comment by jfb54** [comment]
Thanks!
