### ISSUE TITLE
no bash file

### ISSUE THREAD

**Issue by RongKaiWeskerMA** [mboudiaf/pytorch-meta-dataset#11]
Hi, thanks for such a nice contribution 
I am just a bit confused that in your data preparation instruction, it says once you obtain the converted data, you can run:
bash scripts/make_records/make_index_files.sh <path_to_converted_data>

However, I cannot find /make_records/make_index_files.sh file in this repo

**Comment by mboudiaf** [comment]
Hi @RongKaiWeskerMA,

Apologies, this file was removed by mistake. I've added it back, please pull and you should see it.
