### ISSUE TITLE
Meta-batch size hard coded to 1

### ISSUE THREAD

**Issue by sudarshan1994** [mboudiaf/pytorch-meta-dataset#8]
Hi, thank you for your implementation. 

The meta-training dataloader seems to have a batch size 1 hard coded in it. I would like to train MAML on this and the default meta batch size there is 4. So I would like to know if there is any particular reason as to why the meta batch size is hard coded to 1.

Thank you!

**Comment by mboudiaf** [comment]
Hi,

Happy it can help :) There is no reason at all for the batch size. The script is just provided as an example for you to see how to use the loader. The specific hyperparameters are for you to set.

**Comment by sudarshan1994** [comment]
Gotcha thanks!
