### ISSUE TITLE
Feature Request: Ideally the episodes generated would be repeatable for a specified seed.

### ISSUE THREAD

**Issue by jfb54** [mboudiaf/pytorch-meta-dataset#9]
The official meta-dataset reader is not deterministic and repeatable, which is frustrating as test runs cannot be directly compared. If your reader could be deterministic (given a seed), that would be a huge win.

**Comment by mboudiaf** [comment]
Hey,

I added this features. You can now specify your seed in args.seed and the sampling of episodes will be deterministic. What I changed was:

- seed the random generator of each worker (the one used for sampling the episodes)
- for ImageNet, the way to load the graph was not deterministic in the original code, so I added an ordering of the leaves after loading https://github.com/mboudiaf/pytorch-meta-dataset/blob/b3be73e09e0e216e9d196cbf51f91e40297700f3/pytorch_meta_dataset/sampling.py#L370 . I used a simple summation as ordering key, which is not theoretically guaranteed to yield a unique ordering. But in practice, it seems to work well :)

Best

**Comment by jfb54** [comment]
Great! I will give it a try.
